apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    hipster-frontend: 
spec:
  containers:
  - name: hipster-frontend
    image: hispter/frontend:1.1
    imagePullPolicy: IfNotPresent
    env:
    - name: PORT
      value: "8080" 
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "product-catalog:8080"
    - name: CURRENCY_SERVICE_ADDR
      value: "currency-service:8080"
    - name: CART_SERVICE_ADDR
      value: "carts-ervice:8080"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "recommendation-service:8080"
    - name: CHECKOUT_SERVICE_ADDR
      value: "checkout-service:8080" 
    - name: SHIPPING_SERVICE_ADDR
      value: "shipping-service:8080"
    - name: AD_SERVICE_ADDR
      value: "ad-service:8080"
  restartPolicy: Never
